# -*- coding: utf-8 -*-
"""Assignment_2ipynb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FkzK-1B-GFdI8TfInRapAfMe6SyOrK7h
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install biopython

# Commented out IPython magic to ensure Python compatibility.
# %pip install screed

import pandas as pd
import numpy as np
import screed 
from collections import Counter
def build_kmers(sequence, ksize):
    kmers = []
    n_kmers = len(sequence) - ksize + 1

    for i in range(n_kmers):
        kmer = sequence[i:i + ksize]
        kmers.append(kmer)

    return kmers

def read_kmers_from_file(filename, ksize):
    all_kmers = []
    for record in screed.open(filename):
        sequence = record.sequence

        kmers = build_kmers(sequence, ksize)
        all_kmers += kmers
        y= len(all_kmers)
        print("sum of",ksize,"Kmers = ",y)
        
    return Counter(all_kmers).most_common()
inputFileName = input("Enter name of input file: ") 
n=int(input("Enter number of kmers : "))
for i in range (1,n+1):
  

  df = pd.DataFrame(read_kmers_from_file(inputFileName, i))
  df.index = np.arange(1, len(df) + 1)
  print(df,"\n")